### ISSUE TITLE
How to add is dirty flag ?

### ISSUE THREAD

**Issue by leolorenzoluis** [jbonfardeci/ShockoutForms#19]
I would like the form to not show that it already has errors and required when it first loaded. I would prefer if it can be when the user started submitting the form. An example is this http://www.knockmeout.net/2011/05/creating-smart-dirty-flag-in-knockoutjs.html 

Could you guide me where to start?

**Comment by jbonfardeci** [comment]
Personally I wouldn’t recommend this since users typically would want to know what fields are required before pressing the submit button. I know our uses would be irritated. However, one idea off the top of my head is to override the CSS for elements with the required attribute by adding a class name such as ‘clean’ to the parent form element.

You could set the border color to normal (whatever that is) by targeting `.spform.clean input[required], .spform.clean select[required] { border-color: #ccc; }`.

Attach a mousedown event handler to the Submit button that removes the clean class from .spform. This will revert the red borders around the input fields. There will be a little more to it but this is the gist of a simple approach.
