### ISSUE TITLE
Allow fill in choice?

### ISSUE THREAD

**Issue by leolorenzoluis** [jbonfardeci/ShockoutForms#20]
How to implement allow fill in choice where user can specify a value like SharePoint?

I can see under setupKoVar that it is setting koObj._isFillInChoice but I don't see any other usages of it?

My idea is that when the modelValue is populated, I want to set a field for that otherOption to be shown in the template which I have done. At a first look I am thinking of comparing this.modelValue and this.options, and whatever is not in the list options, then set that one as the otherOption field.

**Comment by jbonfardeci** [comment]
This feature is on the TODO list. It hasn’t yet been implemented due to level of complexity for the time being.

You can work around by created a text column ‘MyFieldNameOther’. If the selected option is ‘Other’, display the ‘MyFieldNameOther’ field, requiring input.

Example:
1. You have a SP choice field named ‘Language’; Include an option for “Other"
2. Set up a second SP text field, ‘LanguageOther’

Markup:

```
<so-select-field params=“val: Language, caption: ‘—Select an Language--’, required: true"></so-select-field>

<!— ko if: Language() == ‘Other' —>
    <so-text-field params=“val: LanguageOther, required: true"></so-text-field>
<!— /ko —>

```

There are other ways to accomplish the same thing such as ‘pushing’ the new option to Language._options - 

```
vm.Language._options().push(’some new option’);
vm.Language._options.valueHasMutated(); // let Knockout know to update the display options

```
