### ISSUE TITLE
errorLogSiteUrl not working for POST

### ISSUE THREAD

**Issue by xichro** [jbonfardeci/ShockoutForms#21]
If I enter the parameter as the following:
`errorLogSiteUrl: '/managedpath/sitecollection/'`

I receive the following error:

> POST http://rootsite/_vti_bin/listdata.svc/ErrorLog 404 (Not Found)

However, it's working for the GET in which it successfully finds the list.

Any help would be appreciated!
Thanks,
Matt

**Comment by jbonfardeci** [comment]
Hi Matt,

I posted a fix for this. Apparently it was using the rootSiteUrl instead of the errorLogUrl. Thank you for bringing it to my attention. I always use the root site for my error log, so I didn't notice. Let me know if you run into any more issues. New patch version is 1.0.7 in JavaScript directory.
